### ISSUE TITLE
Flesh out Gemfile

### ISSUE THREAD

**Issue by arlandism** [twitchtv/twirp-ruby#28]
While working on #26, I wanted to run tests but noticed that rake and minitest were missing from the Gemfile. This seems like it'd be useful to establish a baseline set of dependencies, and their versions, for contributors.

**Comment by arlandism** [comment]
The `rake` part of this seems to be covered by #29

**Comment by marioizquierdo** [comment]
Added minitest as development dependency. Thanks!
