### ISSUE TITLE
Update rubygems.org

### ISSUE THREAD

**Issue by mastahyeti** [twitchtv/twirp-ruby#47]
It looks like the latest release in this repository is 1.4.0, but the latest version of rubygems.org is 1.2.0. Would it be possible to publish the missing versions? Thanks.

**Comment by marioizquierdo** [comment]
Thanks!

I added the latest release on rubygems: https://rubygems.org/gems/twirp/versions/1.4.1

**Comment by mastahyeti** [comment]
Thanks
