### ISSUE TITLE
server as rackup

### ISSUE THREAD

**Issue by dudo** [twitchtv/twirp-ruby#62]
Great library! Love the option to lean on protobufs without the weight of grpc. 

While following the examples, I thought that a `config.ru` might flow a bit better, though I'm no expert. I prefer that I can pass options to rackup at runtime, vs hard coding them. I've created a file that does *not* work, and I'm wondering if maybe you could point me in the right direction?

```ruby
# config.ru

# Instantiate Service
handler = CardService::Handler.new()
service = CardServiceService.new(handler)

# Mount on webserver
path_prefix = '/twirp/' + service.full_name
server = WEBrick::HTTPServer.new
server.mount path_prefix, Rack::Handler::WEBrick, service

run server
```

Then loading the server with `rackup -o '0.0.0.0' -p '50052'` (kept the grpc port =P)

When calling the server, I get 

```
NoMethodError: undefined method `call' for #<WEBrick::HTTPServer:0x000056158d21b828>
```

**Comment by marioizquierdo** [comment]
You don't need to use WEBrick explicitly, rackup will [pick the best server available](https://github.com/rack/rack/wiki/%28tutorial%29-rackup-howto#auto-selection-of-a-server) based on environment information.

Perhaps you could explicitly handle the route prefix with a little Rack proc that reads the [Rack env](https://webapps-for-beginners.rubymonstas.org/rack/rack_env.html) to see if the prefix is included:

```rb
require "twirp"

handler = CardService::Handler.new()
service = CardServiceService.new(handler)

app = proc do |env|  
  if env["PATH_INFO"].start_with? "/twirp"
    env["PATH_INFO"] = env["PATH_INFO"].delete_prefix("/twirp")
    service.call(env)
  else
    bad_route_twerr = Twirp::Error.bad_route("Route must have prefix: /twirp")
    Twirp::Service.error_response(bad_route_twerr)
  end
end

run app  
```

Or maybe you could use something like [Rack::Mount](https://github.com/jm/rack-mount) to handle the prefix.

There are so many different ways to do this ... anything that works for a Rack app works for a Twirp app.

**Comment by dudo** [comment]
The proc! That does it. Thank you so much!
