### ISSUE TITLE
Invalid `v7.1.2` release breaking `go get` to latest

### ISSUE THREAD

**Issue by promiseofcake** [twitchtv/twirp-ruby#69]
It seems like there is a typo or something with the [v7.1.2](https://github.com/twitchtv/twirp-ruby/releases/tag/v7.1.2) release (should it be `v1.7.2`?. This makes the `go get github.com/twitchtv/twirp-ruby/protoc-gen-twirp_ruby` command always default to the `v7.1.2` release even when expecting to get `v.1.8.0`.

Example:

```bash
$ go get github.com/twitchtv/twirp-ruby/protoc-gen-twirp_ruby
go get: upgraded github.com/twitchtv/twirp-ruby v1.7.2 => v7.1.2+incompatible
```

It's unclear why this is happening as a fresh-clone of the repo (and Github inspection) does not contain a tag for `v7.1.2`, any insight on what we can do to address this?

Also see: https://libraries.io/go/github.com%2Ftwitchtv%2Ftwirp-ruby which lists the v7.1.2 release.

**Comment by wmatveyenko** [comment]
We are unable to remove that from libraries.io. The latest 1.9.0 release is there.
