### ISSUE TITLE
Can we relax faraday version constraint?

### ISSUE THREAD

**Issue by shouichi** [twitchtv/twirp-ruby#84]
The current constraint is `< 2` but the latest faraday as of today is v2.3.0. Is it possible to relax the constraint to `< 3`?

https://rubygems.org/gems/faraday

**Comment by rebelagentm** [comment]
Just adding a +1 for this. 😃

**Comment by arthurnn** [comment]
I believe @gaffneyc had a PR for this. I gave my 👍  to it.
